language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: T/cTVoSFkAzo8xbOo0ZCeJbOld9Ab5AFDvrVe28rfFLrMGQu2bgWSGdDB05pv9VbptgrQF4KesK3bIU28QT4vyxTcNiSV2S0XXefkJsxSn+LeXoUyl2amK5LsKoBZGicXVFsw4R3xBhMljRTBV1ysmqmc0P5+zfAzvQMuotMIQ6maQEZTGZLue8CbskxiVfJl72WEgxZvvV5XfRswEVMHPZlr4uf7XCsKCfb8IupppGDEle8xyXOlBC/dlmETq9j6K7meXOGo4lwYbFIkRA0HeFxMDcq2GmsWIQSZ+7JhZPJT8LDkCqrnNn8GzlKQznU3ofx1YEu50tKrBwz7iSRJ+sN9nn8BQgMX5eyAc8tQmLi2FsLrRhTNfoMDo18bqA5JYvKe8/KF6pEIvuEw/lyjfm7b5KGOz3yDTJVSw13wddkC8RGZ/uOrfTC4SaExaA2eKXHNL83agMNhGqUXpdkjUoF9sQumVzZ5PzYMvTJHfkLbjx2Otx13HyqG830Cx5lupfshmTVVlyciVduAZhRMi/0BkBm2H/GTVG/YlyFYZZ6p1FOkmc4iGAbBZCUSzl6UU/S8AW28MbfoW5klIQBQ6iJclr8Yl+jNCwYwDW0etVvBO/9Nl2/QYIxn/g0ZTzsBHaxzkbWAsns9ct4CusufiG4hBxoPO/YB4X//ODLwE8=
  on:
    branch: master
    tags: true
    repo: deg-skeletor/skeletor-plugin-watch
